version: '3.8'

networks:
  one-system-network:
    driver: bridge

services:
  app:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: one-system-app
    restart: unless-stopped
    ports:
      - "95:80"
    volumes:
      - .:/var/www/html:delegated
    depends_on:
      - php
      - redis
    networks:
      - one-system-network

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: one-system-php
    restart: unless-stopped
    volumes:
      - .:/var/www/html:delegated
    networks:
      - one-system-network
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7-alpine
    container_name: one-system-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass cas_redis_password
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - one-system-network
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  composer:
    image: composer:latest
    container_name: one-system-composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['composer']

  artisan:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: one-system-artisan
    volumes:
      - .:/var/www/html:delegated
    working_dir: /var/www/html
    entrypoint: ['php', 'artisan']
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  redis_data:
    driver: local