[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:php-fpm]
#command=php-fpm
command=/usr/local/sbin/php-fpm -F
#user=www
autostart=true
autorestart=true
priority=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
#command=nginx -g "daemon off;"
command=/usr/sbin/nginx -g 'daemon off;'
user=root
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
# Use the full path to the PHP executable
command=/usr/local/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3 --max-time=3600
user=www
autostart=true
autorestart=true
numprocs=2
stopwaitsecs=3600
# Send logs to Docker's log collector (recommended)
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:laravel-scheduler]
# Use the full path to the PHP executable
command=/usr/local/bin/php /var/www/html/artisan schedule:work
user=www
autostart=true
autorestart=true
# Send logs to Docker's log collector (recommended)
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0